### ISSUE TITLE
(Bug) Lock icons persist on channels and categories if access is granted to them

### ISSUE THREAD

**Issue by Razzaline** [JustOptimize/return-ShowHiddenChannels#50]
After being granted access to some channels and categories that were previously hidden, the lock icon on them did not go away. They have persisted with disabling the lock icon in settings, disabling the plugin, restarting Discord, and uninstalling BetterDiscord.

**Comment by JustOptimize** [comment]
This problem solves itself with time or by restarting Discord, no need to do all the steps you mentioned.

I recognise this is a bug but jeez

**Comment by Razzaline** [comment]
It hasn't solved itself for me after multiple restarts, so I'm not really sure what to do

**Comment by Razzaline** [comment]
Sorry, I accidentally closed this. >.<

**Comment by JustOptimize** [comment]
> It hasn't solved itself for me after multiple restarts, so I'm not really sure what to do

After a restart, it is impossible to still see the name of the channel you gained access to with the lock icon.
Added a patch to make it fix itself (Beta) even if the channel name won't update instantly, see the unstable branch last commit for more info

**Comment by JustOptimize** [comment]
Check latest version with `V2 Icons` enabled in the plugin settings and tell me if this fixes your issue

**Comment by HistoricTheater** [comment]
> Check latest version with `V2 Icons` enabled in the plugin settings and tell me if this fixes your issue

Using the V2 setting the yellow lock icon is still present on the left side of the category and channel while the grey icon is also present on the right side of only channels. I also noticed that if there is any amount of locked channels in a category that has channels you have permission too, the category shows the yellow lock icon for the category. It should only show the specific channel as being locked and not the entire category if the entire category has channels that you have access too(previous behavior). As present if a category has 10 channels,9 of which you have access too and 1 channel you do not, locking the entire category is misleading vs a category that has 3 channels all which you do not have access too

**Comment by Razzaline** [comment]
I still see the lock icon on the previously hidden channels and categories. I think Discord is caching the modified channel names somewhere, because if I remove the config directory (~/.config/discord) the channels are back to normal.

**Comment by JustOptimize** [comment]
The fact that the yellow lock icons are still visible means that you have not restarted the discord client after the update.

Whether or not a category shows the lock icon is because discord considers it to be hidden, and if it is hidden it will show the lock icon, and I consider that to be intentional behavior.

**Comment by JustOptimize** [comment]
> I still see the lock icon on the previously hidden channels and categories. I think Discord is caching the modified channel names somewhere, because if I remove the config directory (~/.config/discord) the channels are back to normal.

Just restart discord, it should fix it

**Comment by Razzaline** [comment]
Restarting Discord alone didn't fix it. I needed to remove the Local Storage.

**Comment by HistoricTheater** [comment]
> The fact that the yellow lock icons are still visible means that you have not restarted the discord client after the update.

I know how to shut down a program bro. Do you have a preferred filehost in which i may upload a full desktop screen recording starting discord from CLI and showing you the yellow icons are in fact still present when using V2 icons as documented? Because they surely are showing after numerous full client shutdowns and launches

> Whether or not a category shows the lock icon is because discord considers it to be hidden, and if it is hidden it will show the lock icon, and I consider that to be intentional behavior.

The previous source code had no such limitations or restriction and was standard behavior for categories in which hidden channels were present with public access channels. Having a lock icon should mean 0 access,having a lock icon on categories that have publicly permissive channels is misleading and can cause problems

**Comment by JustOptimize** [comment]
I will think about it this afternoon, the strange thing is that I can't reproduce it.
What version of discord and operating system are you on?

**Comment by Soulivan71** [comment]
Im using > Ptb 154876 (57adf52) Host 1.0.1019

**Comment by soudblox** [comment]
I fixed this issue by disabling the lock icon in settings, then re-enabling it.
